actions

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -55,3 +55,16 @@ jobs:
        # Apply the changes to GCP
       - name: Destroy Terraform
         run: terraform ${{inputs.actions}} -auto-approve tfplan
+      - name: Terraform Apply or Destroy
+        run: |
+          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
+            terraform apply -auto-approve
+          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
+            # Create a plan for destruction
+            terraform plan -destroy -out=tfplan
+            # Apply the destruction plan
+            terraform apply -auto-approve "tfplan"
+          else
+            echo "Invalid action specified. Use 'apply' or 'destroy'."
+            exit 1
+          fi
